DROP TABLE `#__cidade`;
DROP TABLE `#__angelgirls_agenda` ;
DROP TABLE `#__angelgirls_email`;
DROP TABLE `#__angelgirls_redesocial` ;
DROP TABLE `#__angelgirls_telefone`;
DROP TABLE `#__angelgirls_endereco`;
DROP TABLE `#__angelgirls_locacao`;
DROP TABLE `#__angelgirls_modelo`;
DROP TABLE `#__angelgirls_fotografo`;
DROP TABLE `#__angelgirls_visitante`;
DROP TABLE `#__angelgirls_equipe` ;
DROP TABLE `#__angelgirls_locacao`;
DROP TABLE `#__angelgirls_tema`;
DROP TABLE `#__angelgirls_sessao`;
DROP TABLE `#__angelgirls_foto_sessao`;
DROP TABLE `#__angelgirls_galeria`;
DROP TABLE `#__angelgirls_foto_galeria`;
DROP TABLE `#__angelgirls_promocao`;
DROP TABLE `#__angelgirls_vt_fotografo`;
DROP TABLE `#__angelgirls_vt_sessao`;
DROP TABLE `#__angelgirls_vt_modelo`;
DROP TABLE `#__angelgirls_vt_foto_sessao`;
DROP TABLE `#__angelgirls_vt_foto_galeria`;
DROP TABLE `#__angelgirls_vt_equipe`;
DROP TABLE `#__angelgirls_vt_galeria`;