
CREATE OR REPLACE VIEW #__angelgirls_perfil (
		`id`, 
		`tipo`,
		`usuario`,
		`nivel`,
		`pontos`,
		`token`,
		`nome_completo`,
		`email_principal`,
		`id_usuario`, 
		`apelido`, 
		`descricao`, 
		`meta_descricao`, 
		`foto_perfil`, 
		`foto_adicional1`,
		`foto_adicional2`, 
		`altura`, 
		`peso`, 
		`busto`, 
		`calsa`, 
		`calsado`, 
		`olhos`, 
		`pele`, 
		`etinia`, 
		`cabelo`, 
		`tamanho_cabelo`, 
		`cor_cabelo`, 
		`outra_cor_cabelo`,
		`profissao`,
		`nascionalidade`,
		`id_cidade_nasceu`,
		`cidade_nasceu`,
        `uf_nasceu`,
		`data_nascimento`,
		`site`,
		`sexo`,
		`cpf`,
		`banco`,
		`agencia`,
		`conta`,
		`custo_medio_diaria`,
		`outro_status`,
		`qualificao_equipe`,
		`audiencia_gostou`,
		`audiencia_ngostou`,
		`audiencia_view`,
		`id_cidade`,
		`cidade_mora`,
        `uf`,
		`status_dado`,
		`id_usuario_criador`, 
		`id_usuario_alterador`, 
		`data_criado`, 
		`data_alterado`) AS

(SELECT  
		`p`.`id`,
		'MODELO' AS `tipo` ,
		`u`.`username` AS `usuario`,
		`p`.`nivel`,
		`p`.`pontos`,
		`p`.`token`,
		`u`.`name` AS `nome_completo`,
		`u`.`email` AS `email_principal`,
		`p`.`id_usuario`, 
		`p`.`nome_artistico` AS `apelido`, 
		`p`.`descricao`, 
		`p`.`meta_descricao`, 
		`p`.`foto_perfil` AS `foto_perfil`, 
		`p`.`foto_inteira` AS `foto_adicional1`,
		`p`.`foto_inteira_horizontal` AS  `foto_adicional2`, 
		`p`.`altura`, 
		`p`.`peso`, 
		`p`.`busto`, 
		`p`.`calsa`, 
		`p`.`calsado`, 
		`p`.`olhos`, 
		`p`.`pele`, 
		`p`.`etinia`, 
		`p`.`cabelo`, 
		`p`.`tamanho_cabelo`, 
		`p`.`cor_cabelo`, 
		`p`.`outra_cor_cabelo`,
		`p`.`profissao`,
		`p`.`nascionalidade`,
		`p`.`id_cidade_nasceu`,
		`cnasceu`.`nome` as `cidade_nasceu`,
        `cnasceu`.`uf` as `uf_nasceu`,
		`p`.`data_nascimento`,
		`p`.`site`,
		`p`.`sexo`,
		`p`.`cpf`,
		`p`.`banco`,
		`p`.`agencia`,
		`p`.`conta`,
		`p`.`custo_medio_diaria`,
		`p`.`status_modelo` AS `outro_status`,
		`p`.`qualificao_equipe`,
		`p`.`audiencia_gostou`,
		`p`.`audiencia_ngostou`,
		`p`.`audiencia_view`,
		`p`.`id_cidade`,
		`cvive`.`nome` as `cidade_mora`,
        `cvive`.`uf` as `uf`,
		`p`.`status_dado`,
		`p`.`id_usuario_criador`, 
		`p`.`id_usuario_alterador`, 
		`p`.`data_criado`, 
		`p`.`data_alterado`  
FROM
		`#__angelgirls_modelo` AS p INNER JOIN
		`#__users` AS u ON p.id_usuario = u.id LEFT JOIN
        `#__cidade` AS cnasceu ON cnasceu.id = p.id_cidade_nasceu  LEFT JOIN
        `#__cidade` AS cvive ON cvive.id = p.id_cidade
WHERE 
		`p`.`status_dado` <> 'REMOVIDO')
UNION
(SELECT  
		`p`.`id`,
		'FOTOGRAFO' AS `tipo` ,
		`u`.`username` AS `usuario`,
		`p`.`nivel`,
		`p`.`pontos`,
		`p`.`token`,
		`u`.`name` AS `nome_completo`,
		`u`.`email` AS `email_principal`,
		`p`.`id_usuario`, 
		`p`.`nome_artistico` AS `apelido`, 
		`p`.`descricao`, 
		`p`.`meta_descricao`, 
		`p`.`nome_foto` AS `foto_perfil`, 
		null AS  `foto_adicional1`,
		null AS   `foto_adicional2`, 
		null AS `altura`, 
		null AS `peso`, 
		null AS `busto`, 
		null AS `calsa`, 
		null AS `calsado`, 
		null AS `olhos`, 
		null AS `pele`, 
		null AS `etinia`, 
		null AS `cabelo`, 
		null AS `tamanho_cabelo`, 
		null AS `cor_cabelo`, 
		null AS `outra_cor_cabelo`,
		`p`.`profissao`,
		`p`.`nascionalidade`,
		`p`.`id_cidade_nasceu`,
		`cnasceu`.`nome` as `cidade_nasceu`,
        `cnasceu`.`uf` as `uf_nasceu`,
		`p`.`data_nascimento`,
		`p`.`site`,
		`p`.`sexo`,
		`p`.`cpf`,
		`p`.`banco`,
		`p`.`agencia`,
		`p`.`conta`,
		`p`.`custo_medio_diaria`,
		null AS `outro_status`,
		`p`.`qualificao_equipe`,
		`p`.`audiencia_gostou`,
		`p`.`audiencia_ngostou`,
		`p`.`audiencia_view`,
		`p`.`id_cidade`,
		`cvive`.`nome` as `cidade_mora`,
        `cvive`.`uf` as `uf`,
		`p`.`status_dado`,
		`p`.`id_usuario_criador`, 
		`p`.`id_usuario_alterador`, 
		`p`.`data_criado`, 
		`p`.`data_alterado`  
FROM
		`#__angelgirls_fotografo` AS p INNER JOIN
		`#__users` AS u ON p.id_usuario = u.id LEFT JOIN
        `#__cidade` AS cnasceu ON cnasceu.id = p.id_cidade_nasceu  LEFT JOIN
        `#__cidade` AS cvive ON cvive.id = p.id_cidade
WHERE 
		`p`.`status_dado` <> 'REMOVIDO')
UNION		
(SELECT  
		`p`.`id`,
		'VISITANTE' AS `tipo` ,
		`u`.`username` AS `usuario`,
		`p`.`nivel`,
		`p`.`pontos`,
		`p`.`token`,
		`u`.`name` AS `nome_completo`,
		`u`.`email` AS `email_principal`,
		`p`.`id_usuario`, 
		`p`.`apelido` AS `apelido`, 
		`p`.`sobre` AS `descricao`, 
		`p`.`meta_descricao`, 
		`p`.`nome_foto` AS `foto_perfil`, 
		null AS  `foto_adicional1`,
		null AS   `foto_adicional2`, 
		null AS `altura`, 
		null AS `peso`, 
		null AS `busto`, 
		null AS `calsa`, 
		null AS `calsado`, 
		null AS `olhos`, 
		null AS `pele`, 
		null AS `etinia`, 
		null AS `cabelo`, 
		null AS `tamanho_cabelo`, 
		null AS `cor_cabelo`, 
		null AS `outra_cor_cabelo`,
		`p`.`profissao`,
		`p`.`nascionalidade`,
		`p`.`id_cidade_nasceu`,
		`cnasceu`.`nome` as `cidade_nasceu`,
        `cnasceu`.`uf` as `uf_nasceu`,
		`p`.`data_nascimento`,
		`p`.`site`,
		`p`.`sexo`,
		`p`.`cpf`,
		`p`.`banco`,
		`p`.`agencia`,
		`p`.`conta`,
		`p`.`custo_medio_diaria`,
		null AS `outro_status`,
		`p`.`qualificao_equipe`,
		`p`.`audiencia_gostou`,
		`p`.`audiencia_ngostou`,
		`p`.`audiencia_view`,
		`p`.`id_cidade`,
		`cvive`.`nome` as `cidade_mora`,
        `cvive`.`uf` as `uf`,
		`p`.`status_dado`,
		`p`.`id_usuario_criador`, 
		`p`.`id_usuario_alterador`, 
		`p`.`data_criado`, 
		`p`.`data_alterado`  
FROM
		`#__angelgirls_visitante` AS p INNER JOIN
		`#__users` AS u ON p.id_usuario = u.id  LEFT JOIN
        `#__cidade` AS cnasceu ON cnasceu.id = p.id_cidade_nasceu  LEFT JOIN
        `#__cidade` AS cvive ON cvive.id = p.id_cidade
WHERE 
		`p`.`status_dado` <> 'REMOVIDO')